#!/usr/bin/env python
from misc.utility.scons_hints import *

import build_scripts.mono_configure as mono_configure

Import("env")
Import("env_modules")

env_mono = env_modules.Clone()

# Configure Mono

mono_configure.configure(env, env_mono)

# Link the Android NativeAOT runtime directly into the native Godot library.
# NativeAOT provides static archives, so they must be linked at build time.
if env["platform"] == "android":
    if env.debug_features and not (env.editor_build and env["store_release"]):
        naot_runtime = "#modules/mono/thirdparty/libnaot-android.debug-static-debug.a"
    else:
        naot_runtime = "#modules/mono/thirdparty/libnaot-android.release-static-release.a"
    env_mono.Append(LIBS=[env_mono.File(naot_runtime)])

# Add sources

env_mono.add_source_files(env.modules_sources, "*.cpp")
env_mono.add_source_files(env.modules_sources, "glue/*.cpp")
env_mono.add_source_files(env.modules_sources, "mono_gd/*.cpp")
env_mono.add_source_files(env.modules_sources, "utils/*.cpp")

if env.editor_build:
    env_mono.add_source_files(env.modules_sources, "editor/*.cpp")
    SConscript("editor/script_templates/SCsub")
